<?php  

use Fpdf\Fpdf;

class PDF extends FPDF
{
    // Fungsi Header
    function Header()
    {
        $this->SetLineWidth(0.5); // Lebar garis
        $this->SetFont('arial', '', 10);
        $this->Cell(0, 10, 'Page :  ' . $this->PageNo(), 0, 0, 'R');
        $this->ln(5);
        $this->Cell(0, 10, 'Tanggal: ' . date('d/m/Y'), 0, 1,'R'); // Menampilkan tanggal dengan format dd/mm/yyyy
        $this->SetFont('Arial', 'B', 20);
        $this->Cell(0, 7, 'Tahura Cafe', 0, 1, 'L');
        $this->Line(10, 32, 200, 32); // Menggambar garis horizontal
        $this->Line(10, 33, 200, 33); // Menggambar garis horizontal
        $this->Ln(5); // Spasi antara judul dan isi
    }

    // Fungsi Footer
    function Footer()
    {
    $this->SetY(-15); // Posisi 15 mm dari bawah
    $this->SetFont('Arial', 'I', 8);
    $this->Cell(0, 10, 'Halaman ' . $this->PageNo(), 0, 0, 'R');
    $this->ln(3);
    $this->Cell(0, 10, 'Tanggal: ' . date('d/m/Y'), 0, 1,'R');
        // Kode Footer (tidak diubah)
    }
}

$dari = '';
$sampai = '';

$pdf = new PDF('P', 'mm', 'A4'); // 'P' untuk orientasi Potrait, ukuran dalam milimeter (80 mm x 150 mm)
$pdf->AddPage();

$pdf->SetFont('Arial','',10);
$pdf->Cell(30,5,"Jenis Laporan",0,0,'L');
$pdf->Cell(3,5,":",0,0,'R');
$pdf->Cell(60,5,"Laporan Transaksi",0,0,'L');
$pdf->Ln();
$pdf->Cell(30,5,"Kasir",0,0,'L');
$pdf->Cell(3,5,":",0,0,'R');
$pdf->Cell(60,5,"Andhika",0,0,'L');
$pdf->Line(10, 48, $pdf->GetPageWidth() - 10, 48); // Koordinat y = 50, x dari 10 ke lebar halaman - 10$pdf->Ln(10); // Menggambar garis horizontal

$pdf->Ln(10);
if(($dari != 0) || ($dari != null)){
    $pdf->Cell(190,5,"Tanggal : ". date('Y-m-d', strtotime($dari)),0,0,'C');
    $pdf->Ln(10);
}elseif($dari && $sampai){
    $pdf->Cell(190,5,"Tanggal : ". date('Y-m-d', strtotime($dari)). ' s.d '. date('Y-m-d', strtotime($dari)),0,0,'C');
    $pdf->Ln(10);
}else{
    $pdf->Cell(190,5,"Tanggal : ". date('Y-m-d'),0,0,'C');
    $pdf->Ln(10);
    
}
// Gunakan data yang diambil
$pdf->Cell(10,6,'No',1,0,'');
$pdf->Cell(42,6,'Nama Produk',1,0,'');
$pdf->Cell(10,6,'Qty',1,0,'');
$pdf->Cell(30,6,'Harga',1,0,'');
$pdf->Cell(30,6,'Sub Total',1,0,'');
$pdf->Cell(13,6,'Diskon',1,0,'');
$pdf->Cell(30,6,'Total',1,0,'');
$pdf->Cell(25,6,'Tanggal',1,0,'');
$pdf->ln();


// $data = $result["trans_id"];
$kasir ='';
$dari_sampai = '';
// $data = "ahai";
$no = 1;
$total_semua = 0;
foreach($result as $data){

    $pdf->Cell(10,6,$no++,1,0,'');
    $prod_nama = $data['nama_produk'];
    $pdf->Cell(42,6,$prod_nama,1,0,'L');
    $qty =  $data['qty'];
    $pdf->Cell(10,6,$qty,1,0,'R');
    $harga = $data['harga'];
    $pdf->Cell(30,6,formatRupiah($harga),1,0,'R');
    $sub_total = $data['sub_total'];
    $pdf->Cell(30,6,formatRupiah($sub_total),1,0,'R');
    $diskon = $data['diskon'] * 100 .'%';
    $pdf->Cell(13,6,$diskon,1,0,'R');
    $total = $data['total'];
    $pdf->Cell(30,6,formatRupiah($total),1,0,'R');
    $tanggal = date('Y-m-d ', strtotime( $data['tanggal']));;
    $pdf->Cell(25,6,$tanggal,1,0,'');
    $total_semua += $total;
    $pdf->Ln();
}

$pdf->Cell(190,3,formatRupiah($total_semua),1,0,'C');





$pdf->Output();

function formatRupiah($angka) {
    $number = preg_replace("/[^0-9]/", "", $angka);
    $split = str_split($number);
    $length = count($split);
    $rupiah = '';
    for ($i = 0; $i < $length; $i++) {
        if (($length - $i) % 3 == 0 && $i != 0) {
            $rupiah .= '.';
        }
        $rupiah .= $split[$i];
    }
    return $rupiah;
}
